openapi: 3.0.3
info:
  title: Project Management API
  version: 1.0.0
  description: A project management API collection for Tech Foring Limited
  contact:
    name: Tanzid Haque
    email: tanzid3@gmail.com
    url: https://github.com/tanzid64
paths:
  /api/comments/{id}/:
    get:
      operationId: comments_retrieve
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      tags:
        - comments
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Retrieve a comment by ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
              example:
                id: 1
                title: "Task 1"
                description: "This is a task description."
                status: "to_do"
                priority: "high"
    put:
      operationId: comments_update
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      tags:
        - comments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
            example:
              title: "Updated Task"
              description: "Updated description of the task."
              status: "in_progress"
              priority: "medium"
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Update a comment by ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
              example:
                id: 1
                title: "Updated Task"
                description: "Updated description of the task."
                status: "in_progress"
                priority: "medium"
    delete:
      operationId: comments_destroy
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      tags:
        - comments
      security:
        - jwtAuth: []
      responses:
        "204":
          description: No response body
  /api/projects/:
    get:
      operationId: projects_list
      description: Retrieve a list of projects
      tags:
        - projects
      security:
        - jwtAuth: []
      responses:
        "200":
          description: List of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
              example:
                - id: 1
                  name: "Project A"
                  description: "Sample project A description."
                  created_at: "2023-12-25T12:00:00Z"
                  updated_at: "2023-12-26T12:00:00Z"
                  owner:
                    id: 1
                    username: "john_doe"
                - id: 2
                  name: "Project B"
                  description: "Sample project B description."
                  created_at: "2023-12-25T12:00:00Z"
                  updated_at: "2023-12-26T12:00:00Z"
                  owner:
                    id: 2
                    username: "jane_doe"
    post:
      operationId: projects_create
      description: Create a new project
      tags:
        - projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"
            example:
              name: "New Project"
              description: "Description for the new project."
      security:
        - jwtAuth: []
      responses:
        "201":
          description: Project created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
              example:
                id: 3
                name: "New Project"
                description: "Description for the new project."
                created_at: "2023-12-27T12:00:00Z"
                updated_at: "2023-12-27T12:00:00Z"
                owner:
                  id: 1
                  username: "john_doe"
  /api/projects/{id}/:
    get:
      operationId: projects_retrieve
      description: Retrieve a single project by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      tags:
        - projects
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Single project details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
              example:
                id: 1
                name: "Project A"
                description: "Sample project A description."
                created_at: "2023-12-25T12:00:00Z"
                updated_at: "2023-12-26T12:00:00Z"
                owner:
                  id: 1
                  username: "john_doe"
components:
  schemas:
    Project:
      type: object
      description: Serializer for Project.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        description:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        owner:
          type: object
          properties:
            id:
              type: integer
            username:
              type: string
      required:
        - id
        - name
        - description
        - created_at
        - updated_at
        - owner
    Task:
      type: object
      description: Serializer for Task.
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
            - to_do
            - in_progress
            - done
        priority:
          type: string
          enum:
            - low
            - medium
            - high
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - id
        - title
        - description
        - status
        - priority
        - created_at
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
